default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: docker
  host: localhost
  pool: 5

development:
  <<: *default
  database: bank_development

test:
  <<: *default
  database: bank_test

production:
  <<: *default
  database: bank_production
  username: <%= ENV[''] %>
  password: <%= ENV[''] %>
